version: "3.7"

services:

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always
    volumes:
      - ./mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./mongodb/data/db:/data/db
    networks:
      - app-tier

  pyapp:
    hostname: pyapp
    container_name: pyapp
    build:
      context: ./pyapp
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongodb
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
